[program:todo]
command=/home/xahizivi/apps/todo/deploy/run.sh
directory=/home/xahizivi/apps/todo
autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=15
stopsignal=TERM
stdout_logfile=/home/xahizivi/apps/todo/logs/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/home/xahizivi/apps/todo/logs/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
